wget www.cc.gatech.edu/dimacs10/archive/data/clustering/G_n_pin_pout.graph.bz2
bunzip2 G_n_pin_pout.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/PGPgiantcompo.graph.bz2
bunzip2 PGPgiantcompo.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/adjnoun.graph.bz2
bunzip2 adjnoun.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/as-22july06.graph.bz2
bunzip2 as-22july06.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/astro-ph.graph.bz2
bunzip2 astro-ph.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/caidaRouterLevel.graph.bz2
bunzip2 caidaRouterLevel.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/celegans_metabolic.graph.bz2
bunzip2 celegans_metabolic.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/celegansneural.graph.bz2
bunzip2 celegansneural.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/chesapeake.graph.bz2
bunzip2 chesapeake.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/cnr-2000.graph.bz2
bunzip2 cnr-2000.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/cond-mat-2003.graph.bz2
bunzip2 cond-mat-2003.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/cond-mat-2005.graph.bz2
bunzip2 cond-mat-2005.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/cond-mat.graph.bz2
bunzip2 cond-mat.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/dolphins.graph.bz2
bunzip2 dolphins.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/email.graph.bz2
bunzip2 email.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/eu-2005.graph.bz2
bunzip2 eu-2005.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/football.graph.bz2
bunzip2 football.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/hep-th.graph.bz2
bunzip2 hep-th.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/in-2004.graph.bz2
bunzip2 in-2004.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/jazz.graph.bz2
bunzip2 jazz.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/karate.graph.bz2
bunzip2 karate.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/lesmis.graph.bz2
bunzip2 lesmis.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/netscience.graph.bz2
bunzip2 netscience.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/polblogs.graph.bz2
bunzip2 polblogs.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/polbooks.graph.bz2
bunzip2 polbooks.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/power.graph.bz2
bunzip2 power.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/preferentialAttachment.graph.bz2
bunzip2 preferentialAttachment.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/road_central.graph.bz2
bunzip2 road_central.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/road_usa.graph.bz2
bunzip2 road_usa.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/smallworld.graph.bz2
bunzip2 smallworld.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/uk-2002.graph.bz2
bunzip2 uk-2002.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/clustering/uk-2007-05.graph.bz2
bunzip2 uk-2007-05.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/coauthor/citationCiteseer.graph.bz2
bunzip2 citationCiteseer.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/coauthor/coAuthorsCiteseer.graph.bz2
bunzip2 coAuthorsCiteseer.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/coauthor/coAuthorsDBLP.graph.bz2
bunzip2 coAuthorsDBLP.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/coauthor/coPapersCiteseer.graph.bz2
bunzip2 coPapersCiteseer.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/coauthor/coPapersDBLP.graph.bz2
bunzip2 coPapersDBLP.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/delaunay/delaunay_n10.graph.bz2
bunzip2 delaunay_n10.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/delaunay/delaunay_n24.graph.bz2
bunzip2 delaunay_n24.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/dyn-frames/hugebubbles-00000.graph.bz2
bunzip2 hugebubbles-00000.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/dyn-frames/hugebubbles-00010.graph.bz2
bunzip2 hugebubbles-00010.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/dyn-frames/hugebubbles-00020.graph.bz2
bunzip2 hugebubbles-00020.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/dyn-frames/hugetrace-00000.graph.bz2
bunzip2 hugetrace-00000.graph.bz2
wget www.cc.gatech.edu/dimacs10/archive/data/dyn-frames/hugetric-00020.graph.bz2
bunzip2 hugetric-00020.graph.bz2